/**
 * Checkout: from a cart to a confirmed, paid order.
 *
 * The sequence is fixed and the failure behaviour at each step is deliberate:
 *
 *   1. Re-price the cart from the catalogue. Never trust a submitted total.
 *   2. Validate the delivery address and find a shipping rate. No rate, no sale.
 *   3. Re-check stock, then create a PENDING order and reserve the stock.
 *   4. Re-validate the discount code (it may have expired since it was typed).
 *   5. Initialise the payment with the amount from step 1.
 *
 * If step 5 fails, the pending order is cancelled and the stock returns to the
 * shelf, because a customer staring at "could not reach the payment provider"
 * must be able to try again immediately.
 *
 * Confirmation is a separate path, entered only by the callback page and the
 * webhook, and both of them verify the transaction with Paystack before calling
 * `settlePayment` — which is the only function that can mark an order paid.
 */

import { db } from './env';
import { randomToken } from './crypto';
import { computeTotals } from './pricing';
import { checkoutPreview, convertCart, toPricedLines, cartView } from './cart';
import { checkDiscount, redeemDiscount } from './discounts';
import { describeStockProblem } from './pricing';
import { ensureCustomerForEmail } from './auth';
import {
  createPendingOrder,
  createPayment,
  findOrderById,
  findOrderByNumber,
  findOrderByReference,
  findPaymentByReference,
  markPaymentFailed,
  markPaymentInitialized,
  orderItems,
  paymentsForOrder,
  settlePayment,
  shipmentsForOrder,
  updateOrderStatus,
  type OrderItemRow,
  type OrderRow,
} from './orders';
import { initializeTransaction, paystackConfigured, verifyTransaction } from './paystack';
import { storeOrigin } from './env';
import { isValidEmail, normaliseEmail } from './auth';

export interface DeliveryAddress {
  firstName: string;
  lastName: string;
  line1: string;
  line2?: string;
  city: string;
  region?: string;
  postalCode?: string;
  country: string;
  phone: string;
}

export interface PlaceOrderInput {
  cartId: string;
  email: string;
  address: DeliveryAddress;
  shippingMethod?: string | undefined;
  discountCode?: string | undefined;
  customerNote?: string | undefined;
  customerId?: string | null | undefined;
}

export type PlaceOrderResult =
  | { ok: true; order: OrderRow; authorizationUrl: string | null; reference: string }
  | { ok: false; error: string; field?: string };

const REQUIRED_ADDRESS_FIELDS: Array<[keyof DeliveryAddress, string]> = [
  ['firstName', 'First name'],
  ['lastName', 'Last name'],
  ['line1', 'Address'],
  ['city', 'City'],
  ['country', 'Country'],
  ['phone', 'Phone number'],
];

/**
 * Validate a delivery address. Returns the name of the first bad field, so the
 * form can point at it rather than printing one generic message.
 */
export function validateAddress(address: Partial<DeliveryAddress>): string | null {
  for (const [field, label] of REQUIRED_ADDRESS_FIELDS) {
    const value = address[field];
    if (typeof value !== 'string' || value.trim().length === 0) return `${label} is required.`;
  }
  const phone = (address.phone ?? '').replace(/[^0-9+]/g, '');
  if (phone.replace(/\D/g, '').length < 7) return 'Enter a phone number the courier can reach you on.';
  if ((address.line1 ?? '').trim().length < 4) return 'Enter a full street address.';
  if ((address.city ?? '').trim().length < 2) return 'Enter a city.';
  return null;
}

function addressSnapshot(address: DeliveryAddress): Record<string, unknown> {
  return {
    firstName: address.firstName.trim(),
    lastName: address.lastName.trim(),
    line1: address.line1.trim(),
    line2: (address.line2 ?? '').trim(),
    city: address.city.trim(),
    region: (address.region ?? '').trim(),
    postalCode: (address.postalCode ?? '').trim(),
    country: address.country.trim(),
    phone: address.phone.trim(),
  };
}

/**
 * Create the order and start the payment.
 *
 * The order is created first, then the payment is initialised against it, and
 * the reference is generated by us — so the reference exists before Paystack is
 * ever called and a network failure cannot leave a charge with no matching row.
 */
export async function placeOrder(input: PlaceOrderInput): Promise<PlaceOrderResult> {
  const email = normaliseEmail(input.email);
  if (!isValidEmail(email)) return { ok: false, error: 'Enter a valid email address.', field: 'email' };

  const addressError = validateAddress(input.address);
  if (addressError) return { ok: false, error: addressError };

  const preview = await checkoutPreview({
    cartId: input.cartId,
    country: input.address.country,
    region: input.address.region,
    city: input.address.city,
    shippingMethod: input.shippingMethod,
    discountCode: input.discountCode,
  });

  if (preview.empty) return { ok: false, error: 'Your cart is empty.' };

  if (preview.stockProblems.length) {
    const problem = preview.stockProblems[0];
    if (problem) return { ok: false, error: describeStockProblem(problem) };
  }

  // An address we cannot quote is an address we cannot serve. Refusing here is
  // better than inventing a rate and discovering the cost at dispatch.
  if (!preview.shipping) {
    return {
      ok: false,
      error: 'We do not yet ship to that address. Contact us and we will arrange it.',
      field: 'country',
    };
  }

  if (!paystackConfigured()) {
    return { ok: false, error: 'Card payment is not configured on this store yet.' };
  }

  const customerId = input.customerId ?? (await ensureCustomerForEmail(email, `${input.address.firstName} ${input.address.lastName}`, input.address.phone));

  const lines = preview.lines.map((line) => ({
    productId: line.productId,
    variantId: line.variantId,
    productSlug: line.productSlug,
    title: line.title,
    variantTitle: line.variantTitle,
    sku: line.sku,
    imageUrl: line.imageUrl,
    unitPriceMinor: line.unitPriceMinor,
    quantity: line.quantity,
  }));

  // Re-check the discount at the last possible moment: a code can expire or hit
  // its ceiling between the cart page and this call.
  let discountMinor = preview.totals.discountMinor;
  let discountCode = '';
  if (input.discountCode && input.discountCode.trim()) {
    const recheck = await checkDiscount(input.discountCode, preview.totals.subtotalMinor);
    if (!recheck.ok) {
      return { ok: false, error: recheck.reason, field: 'discountCode' };
    }
    discountCode = recheck.discount.code;
    const recomputed = computeTotals({
      lines: toPricedLines(preview.lines),
      shippingMinor: preview.shipping.amountMinor,
      discount: recheck.rule,
    });
    discountMinor = recomputed.discountMinor;
  }

  const totals = computeTotals({
    lines: toPricedLines(preview.lines),
    shippingMinor: preview.shipping.amountMinor,
    discount: discountCode
      ? { code: discountCode, kind: 'fixed', value: discountMinor, minimumSubtotalMinor: 0 }
      : null,
  });

  const order = await createPendingOrder({
    customerId,
    email,
    currency: preview.currency,
    lines,
    subtotalMinor: totals.subtotalMinor,
    discountMinor,
    shippingMinor: totals.shippingMinor,
    taxMinor: totals.taxMinor,
    totalMinor: totals.totalMinor,
    discountCode,
    shippingMethod: preview.shipping.method,
    shippingAddress: addressSnapshot(input.address),
    billingAddress: addressSnapshot(input.address),
    customerNote: input.customerNote ?? '',
  });

  const reference = `OZK${Date.now().toString(36).toUpperCase()}${randomToken(6).replace(/[^A-Za-z0-9]/g, '').slice(0, 6).toUpperCase()}`;
  await createPayment({
    orderId: order.id,
    reference,
    amountMinor: order.total_minor,
    currency: order.currency,
  });

  const initialized = await initializeTransaction({
    email,
    amountMinor: order.total_minor,
    currency: order.currency,
    reference,
    callbackUrl: `${storeOrigin()}/checkout/callback?reference=${encodeURIComponent(reference)}`,
    metadata: {
      order_number: order.number,
      order_id: order.id,
      custom_fields: [
        { display_name: 'Order', variable_name: 'order', value: order.number },
      ],
    },
  });

  if (!initialized.ok) {
    // Give the stock back. The customer must be able to retry straight away, and
    // an order nobody can pay for must not hold the last Medium hostage.
    await markPaymentFailed(reference, initialized.message);
    try {
      await updateOrderStatus({
        orderId: order.id,
        to: 'cancelled',
        actor: null,
        note: `Payment could not be started: ${initialized.message}`,
      });
    } catch (error) {
      console.error('[checkout] could not cancel the order after a failed initialise', order.id, error);
    }
    return { ok: false, error: initialized.message };
  }

  await markPaymentInitialized(reference, initialized.authorizationUrl);
  await convertCart(input.cartId);

  return { ok: true, order, authorizationUrl: initialized.authorizationUrl, reference };
}

export type ConfirmResult =
  | { ok: true; order: OrderRow; alreadySettled: boolean }
  | { ok: false; error: string };

/**
 * Confirm a payment. Called by the callback page and by the webhook.
 *
 * It does not believe either caller: it asks Paystack what happened, compares
 * the amount, and only then lets `settlePayment` touch the order. Running it
 * twice is safe, which is the whole point — the callback and the webhook
 * routinely race, and whichever arrives second must be a no-op.
 */
export async function confirmOrderPayment(reference: string): Promise<ConfirmResult> {
  const payment = await findPaymentByReference(reference);
  if (!payment) return { ok: false, error: 'We have no record of that payment reference.' };

  const order = await findOrderById(payment.order_id);
  if (!order) return { ok: false, error: 'We have no record of that order.' };

  /*
   * A SETTLED PAYMENT WHOSE ORDER IS NOT PAID IS NOT FINISHED.
   *
   * This returned success immediately whenever the payment row was already
   * settled, without asking whether the order had been marked paid. It usually
   * had — the webhook and the callback race, and the second one is a no-op.
   *
   * But `settlePayment` writes the payment row first and the order second, and a
   * process that stops in between leaves a payment that is `success` with an
   * order still `pending`. Every later call then reported "already settled" and
   * changed nothing: the customer has paid, the shop believes they have not, and
   * no retry or webhook redelivery could ever fix it.
   *
   * So the settled case checks the ORDER too, and can still call `settlePayment`
   * — which is idempotent, re-runs its amount check, and is the only thing that
   * marks an order paid. The gateway is still not contacted: the payment row
   * already records that it was verified.
   */
  if (payment.settled_at && payment.status === 'success') {
    if (order.status !== 'pending' && order.status !== 'failed') {
      return { ok: true, order, alreadySettled: true };
    }
    const repaired = await settlePayment({
      reference,
      amountMinor: payment.amount_minor,
      currency: payment.currency,
      providerReference: payment.provider_reference ?? null,
      channel: payment.channel ?? null,
      gatewayResponse: payment.gateway_response ?? null,
      raw: {},
    });
    return { ok: true, order: repaired.order ?? order, alreadySettled: true };
  }

  const verified = await verifyTransaction(reference);
  if (!verified.ok) return { ok: false, error: verified.message };

  if (!verified.paid) {
    await markPaymentFailed(reference, `Paystack reports status "${verified.status}"`, verified.payload);
    return { ok: false, error: `That payment was not completed (${verified.status}).` };
  }

  const settlement = await settlePayment({
    reference,
    amountMinor: verified.amountMinor,
    currency: verified.currency,
    providerReference: verified.providerId,
    channel: verified.channel,
    gatewayResponse: verified.gatewayResponse,
    raw: verified.payload,
  });

  if (settlement.order && settlement.order.discount_code) {
    // Counting the redemption here means the quantity in the database is the
    // number of orders actually paid for with the code.
    await redeemDiscount(settlement.order.discount_code);
  }

  const finalOrder = settlement.order ?? order;
  if (finalOrder.payment_status !== 'paid') {
    return { ok: false, error: 'The payment was received but the order total did not match. We will contact you.' };
  }

  return { ok: true, order: finalOrder, alreadySettled: !settlement.changed };
}

export interface OrderView {
  order: OrderRow;
  items: OrderItemRow[];
  payments: Awaited<ReturnType<typeof paymentsForOrder>>;
  shipments: Awaited<ReturnType<typeof shipmentsForOrder>>;
}

export async function orderView(orderId: string): Promise<OrderView | null> {
  const order = await findOrderById(orderId);
  if (!order) return null;
  const [items, payments, shipments] = await Promise.all([
    orderItems(order.id),
    paymentsForOrder(order.id),
    shipmentsForOrder(order.id),
  ]);
  return { order, items, payments, shipments };
}

export async function orderViewByNumber(number: string): Promise<OrderView | null> {
  const order = await findOrderByNumber(number);
  if (!order) return null;
  return orderView(order.id);
}

export async function orderViewByReference(reference: string): Promise<OrderView | null> {
  const order = await findOrderByReference(reference);
  if (!order) return null;
  return orderView(order.id);
}

/**
 * May this viewer see this order?
 *
 * The rule is: the owner by account, or the owner by email, or staff. Nothing
 * else. Order numbers are sequential and therefore guessable, so this check is
 * the only thing standing between a stranger and somebody's address and phone
 * number.
 */
export function canViewOrder(input: {
  order: OrderRow;
  viewerCustomerId: string | null;
  viewerEmail: string | null;
  viewerIsStaff: boolean;
}): boolean {
  if (input.viewerIsStaff) return true;
  if (input.viewerCustomerId && input.order.customer_id === input.viewerCustomerId) return true;
  if (input.viewerEmail && input.order.email.toLowerCase() === input.viewerEmail.toLowerCase()) return true;
  return false;
}

/** A receipt-safe reference for the confirmation page. */
export async function paymentReferenceFor(orderId: string): Promise<string | null> {
  const row = await db()
    .prepare(`SELECT reference FROM payments WHERE order_id = ?1 ORDER BY created_at DESC LIMIT 1`)
    .bind(orderId)
    .first<{ reference: string }>();
  return row?.reference ?? null;
}

/** Used by the admin cancel action, which also returns stock. */
export async function cancelOrder(orderId: string, note: string, actor: { id: string; email: string } | null): Promise<OrderRow> {
  return updateOrderStatus({ orderId, to: 'cancelled', actor, note });
}
