import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, Minus, Plus, Trash2 } from 'lucide-react';
import { StoreLayout, PageIntro } from '@/store/layout';
import { useCart } from '@/store/cart';
import { products, money } from '@/store/catalog';
import { storeHead } from '@/store/head';
import { Button } from '@/components/ui/button';
export const Route = createFileRoute('/cart')({ head: () => storeHead('Your cart', 'Review your selections from the Ozikoro Store.'), component: Cart });
function Cart() { const { items, update } = useCart(); const subtotal = items.reduce((sum, item) => sum + (products.find((p) => p.slug === item.slug)?.price || 0) * item.quantity, 0); return <StoreLayout><PageIntro eyebrow="Your selection" title="Your cart"/>{items.length ? <div className="site-container grid lg:grid-cols-[1fr_340px] gap-12"><div className="border-t border-border">{items.map((item) => { const p = products.find((product) => product.slug === item.slug); if (!p) return null; return <div key={`${item.slug}-${item.variant}`} className="flex gap-5 border-b border-border py-6"><Link to="/products/$slug" params={{ slug: p.slug }} className="w-24 sm:w-32 shrink-0 aspect-[4/5] bg-secondary"><img src={p.image} alt={p.title} className="w-full h-full object-cover"/></Link><div className="flex-1 min-w-0"><p className="eyebrow">{p.category}</p><Link to="/products/$slug" params={{ slug: p.slug }} className="font-display text-2xl block mt-1">{p.title}</Link><p className="text-xs text-muted-foreground mt-2">{item.variant}</p><div className="flex items-center gap-4 mt-5"><div className="border border-border flex items-center"><Button variant="ghost" size="icon" aria-label="Decrease quantity" onClick={() => update(item.slug, item.variant, item.quantity - 1)}><Minus size={14}/></Button><span className="w-6 text-center text-sm">{item.quantity}</span><Button variant="ghost" size="icon" aria-label="Increase quantity" onClick={() => update(item.slug, item.variant, item.quantity + 1)}><Plus size={14}/></Button></div><Button variant="ghost" size="icon" title="Remove item" aria-label="Remove item" onClick={() => update(item.slug, item.variant, 0)}><Trash2 size={16}/></Button></div></div><p className="text-sm whitespace-nowrap">{money(p.price * item.quantity)}</p></div>; })}</div><aside className="bg-secondary p-7 h-fit"><h2 className="font-display text-3xl">Order summary</h2><div className="flex justify-between border-b border-border py-6 text-sm"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><p className="text-xs text-muted-foreground leading-relaxed mt-5">Shipping and delivery expectations will be confirmed before payment.</p><Button asChild className="w-full h-12 mt-7"><Link to="/checkout">Continue to checkout <ArrowRight size={16}/></Link></Button><Link to="/shop" className="block text-center text-xs underline mt-5">Continue shopping</Link></aside></div> : <div className="site-container py-20 text-center border-t border-border"><p className="font-display text-3xl">Nothing here just yet.</p><p className="text-muted-foreground mt-3">Explore the store and find something to take with you.</p><Button asChild className="mt-8"><Link to="/shop">Shop all products <ArrowRight size={16}/></Link></Button></div>}</StoreLayout>; }
