import { Link, useLocation } from '@tanstack/react-router';
import { Search, ShoppingBag, UserRound, Menu, ArrowUpRight, X } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { useCart } from './cart';
const nav = [{ label: 'Shop', to: '/shop' }, { label: 'Collections', to: '/collections' }, { label: 'Books & Publications', to: '/collections/books-publications' }, { label: 'Apparel', to: '/collections/apparel' }, { label: 'Cultural Goods', to: '/collections/prints-posters' }, { label: 'About', to: '/about' }] as const;
export function StoreLayout({ children, minimal = false }: { children: ReactNode; minimal?: boolean }) {
  const { count } = useCart(); const [menuOpen, setMenuOpen] = useState(false); const location = useLocation();
  return <div className="min-h-screen bg-background text-foreground font-sans">
    {!minimal && <div className="bg-primary text-primary-foreground text-center py-2 text-[11px] font-medium tracking-wide">Objects for a culture in motion. Thoughtfully made, meaningfully kept.</div>}
    <header className="border-b border-border bg-background relative z-20"><div className="site-container flex h-[76px] items-center justify-between gap-4">
      {!minimal && <Button variant="ghost" size="icon" className="lg:hidden" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button>}
      <Link to="/" className="font-display text-[31px] font-semibold leading-none text-foreground" aria-label="Ozikoro Store home">ozikoro<span className="text-primary">.</span><span className="block font-sans text-[9px] uppercase tracking-[0.3em] font-semibold mt-1">The store</span></Link>
      {!minimal && <nav className="hidden lg:flex items-center gap-6 xl:gap-8 text-[12px] font-medium"><Link to="/shop" className={location.pathname === '/shop' ? 'text-primary' : 'hover:text-primary'}>Shop</Link><Link to="/collections" className="hover:text-primary">Collections</Link><Link to="/collections/books-publications" className="hover:text-primary">Books & Publications</Link><Link to="/collections/apparel" className="hover:text-primary">Apparel</Link><Link to="/collections/prints-posters" className="hover:text-primary">Cultural Goods</Link><Link to="/about" className="hover:text-primary">About</Link></nav>}
      <div className="flex items-center gap-1 sm:gap-2"><Button variant="ghost" size="icon" asChild title="Search"><Link to="/search" aria-label="Search"><Search /></Link></Button>{!minimal && <Button variant="ghost" size="icon" asChild title="Account"><Link to="/account" aria-label="Account"><UserRound /></Link></Button>}<Button variant="ghost" size="icon" asChild title="Cart"><Link to="/cart" aria-label={`Cart, ${count} items`} className="relative"><ShoppingBag />{count > 0 && <span className="absolute -top-1 -right-1 bg-primary text-primary-foreground rounded-full text-[10px] h-4 min-w-4 flex items-center justify-center">{count}</span>}</Link></Button></div>
    </div>{menuOpen && !minimal && <nav className="lg:hidden border-t border-border bg-background px-6 py-4 flex flex-col gap-4 text-sm">{nav.map((item) => <Link key={item.label} to={item.to} onClick={() => setMenuOpen(false)}>{item.label}</Link>)}</nav>}</header>
    <main>{children}</main>
    {!minimal && <footer className="bg-ink text-ink-foreground mt-20"><div className="site-container py-16 grid gap-12 md:grid-cols-[2fr_1fr_1fr_1fr]"><div><div className="font-display text-4xl">ozikoro.</div><p className="text-sm text-ink-muted max-w-xs leading-relaxed mt-5">Culture is not a thing of the past. It is something we carry forward.</p></div><div><p className="footer-heading">Explore</p><Link to="/shop">Shop all</Link><Link to="/collections">Collections</Link><Link to="/about">Our story</Link></div><div><p className="footer-heading">Help</p><Link to="/shipping-returns">Shipping & returns</Link><Link to="/account/orders">Order history</Link><Link to="/about">Contact</Link></div><div><p className="footer-heading">Ozikoro</p><a href="https://ozikoro.com" target="_blank" rel="noreferrer">Ozikoro <ArrowUpRight size={12}/></a><a href="https://ndebe.org" target="_blank" rel="noreferrer">Ńdébé <ArrowUpRight size={12}/></a></div></div><div className="site-container border-t border-ink-line py-5 text-xs text-ink-muted flex flex-wrap justify-between gap-2"><span>© {new Date().getFullYear()} Ozikoro. All rights reserved.</span><span>Made for culture, made to last.</span></div></footer>}
  </div>;
}
export function PageIntro({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) { return <section className="site-container pt-12 pb-9 md:pt-16 md:pb-12">{eyebrow && <p className="eyebrow mb-4">{eyebrow}</p>}<h1 className="font-display text-4xl md:text-6xl leading-[1.08] max-w-3xl">{title}</h1>{description && <p className="text-muted-foreground max-w-xl mt-5 leading-relaxed">{description}</p>}</section>; }
