/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteRouteImport } from './routes/checkout/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminOrdersRouteRouteImport } from './routes/admin/orders/route'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminProductsRouteRouteImport } from './routes/admin/products/route'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutCallbackRouteImport } from './routes/checkout.callback'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as OidcCallbackRouteImport } from './routes/oidc.callback'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as AccountOrdersNumberRouteImport } from './routes/account/orders.$number'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminOrdersNumberRouteImport } from './routes/admin/orders.$number'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsSlugRouteImport } from './routes/admin/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRouteRoute = AdminOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRouteRoute = AdminProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const CheckoutCallbackRoute = CheckoutCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => CheckoutRouteRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OidcCallbackRoute = OidcCallbackRouteImport.update({
  id: '/oidc/callback',
  path: '/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const AccountOrdersNumberRoute = AccountOrdersNumberRouteImport.update({
  id: '/account/orders/$number',
  path: '/account/orders/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRouteRoute,
} as any)
const AdminOrdersNumberRoute = AdminOrdersNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => AdminOrdersRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const AdminProductsSlugRoute = AdminProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/search': typeof SearchRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/oidc/callback': typeof OidcCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/account/orders/$number': typeof AccountOrdersNumberRoute
  '/admin/orders/$number': typeof AdminOrdersNumberRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/search': typeof SearchRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/oidc/callback': typeof OidcCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/account/orders/$number': typeof AccountOrdersNumberRoute
  '/admin/orders/$number': typeof AdminOrdersNumberRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/search': typeof SearchRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/checkout/callback': typeof CheckoutCallbackRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/oidc/callback': typeof OidcCallbackRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/account/orders/$number': typeof AccountOrdersNumberRoute
  '/admin/orders/$number': typeof AdminOrdersNumberRoute
  '/admin/products/$slug': typeof AdminProductsSlugRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/products'
    | '/about'
    | '/cart'
    | '/contact'
    | '/privacy'
    | '/refunds'
    | '/search'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/audit'
    | '/admin/discounts'
    | '/admin/permissions'
    | '/admin/seo'
    | '/checkout/callback'
    | '/collections/$slug'
    | '/oidc/callback'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/checkout/'
    | '/collections/'
    | '/account/orders/$number'
    | '/admin/orders/$number'
    | '/admin/products/$slug'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/about'
    | '/cart'
    | '/contact'
    | '/privacy'
    | '/refunds'
    | '/search'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/admin/audit'
    | '/admin/discounts'
    | '/admin/permissions'
    | '/admin/seo'
    | '/checkout/callback'
    | '/collections/$slug'
    | '/oidc/callback'
    | '/products/$slug'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/collections'
    | '/account/orders/$number'
    | '/admin/orders/$number'
    | '/admin/products/$slug'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/products'
    | '/about'
    | '/cart'
    | '/contact'
    | '/privacy'
    | '/refunds'
    | '/search'
    | '/shipping-returns'
    | '/shop'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/audit'
    | '/admin/discounts'
    | '/admin/permissions'
    | '/admin/seo'
    | '/checkout/callback'
    | '/collections/$slug'
    | '/oidc/callback'
    | '/products/$slug'
    | '/account/'
    | '/admin/'
    | '/checkout/'
    | '/collections/'
    | '/account/orders/$number'
    | '/admin/orders/$number'
    | '/admin/products/$slug'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CheckoutRouteRoute: typeof CheckoutRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SearchRoute: typeof SearchRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  OidcCallbackRoute: typeof OidcCallbackRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  AccountOrdersNumberRoute: typeof AccountOrdersNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/checkout/callback': {
      id: '/checkout/callback'
      path: '/callback'
      fullPath: '/checkout/callback'
      preLoaderRoute: typeof CheckoutCallbackRouteImport
      parentRoute: typeof CheckoutRouteRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oidc/callback': {
      id: '/oidc/callback'
      path: '/oidc/callback'
      fullPath: '/oidc/callback'
      preLoaderRoute: typeof OidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/account/orders/$number': {
      id: '/account/orders/$number'
      path: '/account/orders/$number'
      fullPath: '/account/orders/$number'
      preLoaderRoute: typeof AccountOrdersNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRouteRoute
    }
    '/admin/orders/$number': {
      id: '/admin/orders/$number'
      path: '/$number'
      fullPath: '/admin/orders/$number'
      preLoaderRoute: typeof AdminOrdersNumberRouteImport
      parentRoute: typeof AdminOrdersRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/products/$slug': {
      id: '/admin/products/$slug'
      path: '/$slug'
      fullPath: '/admin/products/$slug'
      preLoaderRoute: typeof AdminProductsSlugRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
  }
}

interface AdminOrdersRouteRouteChildren {
  AdminOrdersNumberRoute: typeof AdminOrdersNumberRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteRouteChildren: AdminOrdersRouteRouteChildren = {
  AdminOrdersNumberRoute: AdminOrdersNumberRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteRouteWithChildren =
  AdminOrdersRouteRoute._addFileChildren(AdminOrdersRouteRouteChildren)

interface AdminProductsRouteRouteChildren {
  AdminProductsSlugRoute: typeof AdminProductsSlugRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteRouteChildren: AdminProductsRouteRouteChildren = {
  AdminProductsSlugRoute: AdminProductsSlugRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteRouteWithChildren =
  AdminProductsRouteRoute._addFileChildren(AdminProductsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminOrdersRouteRoute: typeof AdminOrdersRouteRouteWithChildren
  AdminProductsRouteRoute: typeof AdminProductsRouteRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminOrdersRouteRoute: AdminOrdersRouteRouteWithChildren,
  AdminProductsRouteRoute: AdminProductsRouteRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CheckoutRouteRouteChildren {
  CheckoutCallbackRoute: typeof CheckoutCallbackRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutRouteRouteChildren: CheckoutRouteRouteChildren = {
  CheckoutCallbackRoute: CheckoutCallbackRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutRouteRouteWithChildren = CheckoutRouteRoute._addFileChildren(
  CheckoutRouteRouteChildren,
)

interface ProductsRouteRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CheckoutRouteRoute: CheckoutRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SearchRoute: SearchRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  OidcCallbackRoute: OidcCallbackRoute,
  AccountIndexRoute: AccountIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  AccountOrdersNumberRoute: AccountOrdersNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
